services:
  client:
    build:
      context: ..
      target: production-stage
      args:
        NEXT_PUBLIC_SUPABASE_URL: https://${HOST_IP}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
        NEXT_PUBLIC_APP_PLATFORM: web
        NEXT_PUBLIC_API_BASE_URL: https://${HOST_IP}
