name: Build with Nix

on:
  push:
    branches: [main]
concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: read
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: readest
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: build with nix
      run: nix build 'github:${{ github.repository }}?ref=${{ github.ref }}' -L  --extra-substituters "https://readest.cachix.org"     
